function stress = PIOLA2EL(lamda)
global DFGRD0 STRETCH_NEW STATEV DTIME ...
       MU  ALPHA  KELAS  ...
       MUVIS ALPHAVIS  KVIS ETADEV ETAVOL ...
       MUVIS_2 ALPHAVIS_2  KVIS_2  ETADEV_2 ETAVOL_2 

DFGRD1=zeros(3,3);
DFGRD1(1,1) = STRETCH_NEW;
DFGRD1(2,2) = lamda;
DFGRD1(3,3) = lamda;
[~, ~, ~, FIRSTPIOLA, ~] = VISCOEL_OGDEN_2EL(DFGRD0, DFGRD1, STATEV, DTIME, ...
                                                             MU, ALPHA, KELAS, ...
                                                             MUVIS, ALPHAVIS, KVIS, ETADEV, ETAVOL, ...
                                                             MUVIS_2, ALPHAVIS_2, KVIS_2, ETADEV_2, ETAVOL_2);
stress = FIRSTPIOLA(2,2);

 